<a href="https://colab.research.google.com/github/AbdouSalamSisawo/TensorOrbit-EDA-Bootcamp/blob/main/day-1-foundations-pandas%20/day_1_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/AbdouSalamSisawo/TensorOrbit-EDA-Bootcamp/blob/main/day-1-foundations-pandas/day_1_notebook.ipynb)

# TensorOrbit EDA Bootcamp — Day 1
### Foundations of Data Science, Python & Pandas

**Instructor:** Abdou Salam Sisawo
**Flow:** Python Fundamentals → Meet Pandas → Working With the Messy Employee Dataset → Guided EDA Challenge

This notebook follows the exact same journey as the Day 1 slide deck, in the same order, so you can
code along live or work through it afterwards on your own. Every section starts with **why** a tool
matters before showing **how** to use it — don't just run the cells, read the questions each one answers.

> 💡 **Tip:** Run cells top to bottom with `Shift + Enter`. If something errors, it's almost always
> because an earlier cell wasn't run yet — scroll up and run from the top.

## 📂 About the dataset

This notebook loads the **Messy Employee Dataset** directly from the TensorOrbit GitHub repo, so
there is nothing to download or upload — it works out of the box in **Google Colab**.

- **Repo copy (used by this notebook):** https://github.com/AbdouSalamSisawo/TensorOrbit-EDA-Bootcamp/blob/main/day-1-foundations-pandas/materials/Messy_Employee_dataset.csv
- **Original Kaggle listing:** https://www.kaggle.com/datasets/desolution01/messy-employee-dataset

If you've cloned the repo and are running this notebook **locally** from inside it, the loader
cell in Part 3 also falls back to the local copy of the CSV automatically — no internet required
once you've cloned it.

---
# Part 1 — Python Fundamentals for Data Analysis

We are **not** learning all of Python here — just enough to read and write Pandas code confidently.
Every idea in this section reappears inside Pandas in Part 3.

## 1.1 Variables & Data Types

*How do we store a value in Python?*

In [1]:
name = "Alice"
age = 25
salary = 50000
remote = True

print(name, age, salary, remote)
print(type(name), type(age), type(salary), type(remote))

Alice 25 50000 True
<class 'str'> <class 'int'> <class 'int'> <class 'bool'>

- `str` = text, `int` = whole number, `float` = decimal, `bool` = True/False, `None` = nothing
- Python figures out the type automatically — no need to declare it up front

## 1.2 Think Before You Code: `"25"` vs `25`

`"25"` and `25` look the same to us. Are they the same to Python?

- Quotes = text (`str`) · No quotes = number (`int`)
- This exact mix-up is why a `Salary` column full of text can't be averaged in Pandas later

In [2]:
a = "25"
b = 25

print(a == b)          # are they equal?
print(type(a), type(b))

try:
    print(a + 5)
except TypeError as e:
    print("Error:", e)   # this is exactly what happens when a numeric column is stored as text

False
<class 'str'> <class 'int'>
Error: can only concatenate str (not "int") to str

## 1.3 Operators

In [3]:
age = 35
salary = 62000
remote = True

# Arithmetic:  +  -  *  /  //  %  **
print(age + 5, salary * 12)

# Comparison:  ==  !=  >  <  >=  <=
print(age > 30)
print(salary >= 50000)

# Logical:  and  or  not
print(age > 30 and remote == True)

40 744000
True
True
True

Remember that last line — we'll write this **exact same logic** to filter an entire spreadsheet
of employees a little later.

## 1.4 Strings

In [4]:
name = "Abdou"

print(name[0])            # indexing — first character
print(name[0:3])          # slicing — first three characters

print(name.lower())
print(name.strip())
print(f"Employee: {name}")   # f-string — combine text and variables

A
Abd
abdou
Abdou
Employee: Abdou

Messy real-world names, emails, and job titles need exactly these tools — later we'll use the
`.str` versions of these same methods on an entire Pandas column at once.

## 1.5 Lists

In [5]:
employees = ["Alice", "Bob", "Charlie"]

print(employees[0])
print(employees[0:2])

employees.append("David")
print(employees)

for employee in employees:
    print(employee)

Alice
['Alice', 'Bob']
['Alice', 'Bob', 'Charlie', 'David']
Alice
Bob
Charlie
David

A list is like one column of values sitting in order — that's exactly what a table column is.

## 1.6 Dictionaries

In [6]:
employee = {
    "name": "Alice",
    "age": 25,
    "department": "HR"
}

print(employee["name"])
print(employee)

Alice
{'name': 'Alice', 'age': 25, 'department': 'HR'}

A DataFrame row behaves a lot like a dictionary — the column name is the key.

## 1.7 Conditions

In [7]:
salary = 62000

if salary > 50000:
    print("High salary")
else:
    print("Other")

High salary

Same 'true or false' logic — later we apply it to a whole column at once as a **Pandas filter**.

## 1.8 Loops

In [8]:
employees = ["Alice", "Bob", "Charlie"]

for employee in employees:
    print(employee)

for i in range(5):
    print(i)

Alice
Bob
Charlie
0
1
2
3
4

Pandas will do this kind of repetition for us automatically — but it helps to see it manually once.

## 1.9 Functions

In [9]:
def calculate_total_salary(salary, bonus):
    return salary + bonus

print(calculate_total_salary(50000, 2000))

52000

## 1.10 Imports — The Bridge to Pandas

This is the exact line every notebook you write from now on will start with.

In [10]:
import pandas as pd
import numpy as np

print("pandas:", pd.__version__)
print("numpy:", np.__version__)

pandas: 2.2.3
numpy: 2.0.2

---
# Part 2 — Meet Pandas

Pandas is a Python library built for working with structured, tabular data — rows and columns,
just like Excel. Nearly every EDA task from here on starts with Pandas.

## 2.1 Series — One Column of Data

In [11]:
s = pd.Series([10, 20, 30])
s

0    10
1    20
2    30
dtype: int64

A Series is a single labelled column of values — think of it as a list, but with an index attached.

## 2.2 DataFrame — A Full Table

In [12]:
sample_df = pd.DataFrame({
    "name": ["Alice", "Bob"],
    "age": [25, 30]
})
sample_df

    name  age
0  Alice   25
1    Bob   30

- Rows = records (one employee per row)
- Columns = variables (name, age, department...)
- Notice the shape: a **dictionary of lists** becomes a table — the exact same key → value
  pattern from section 1.6, now holding entire columns instead of single values.

---
# Part 3 — Working With the Messy Employee Dataset

**Dataset:** Messy Employee Dataset (synthetic HR data — **1,020 rows, 12 columns**)
**Source:** https://www.kaggle.com/datasets/desolution01/messy-employee-dataset
**Repo copy:** `day-1-foundations-pandas/materials/Messy_Employee_dataset.csv`

Columns: `Employee_ID`, `First_Name`, `Last_Name`, `Age`, `Department_Region`, `Status`,
`Join_Date`, `Salary`, `Email`, `Phone`, `Performance_Score`, `Remote_Work`

Real data-quality issues you'll actually find in this file as we go:
- Missing `Age` (~21% of rows) and a smaller number of missing `Salary` values
- A compound `Department_Region` column (e.g. `"DevOps-California"`) mixing two variables together
- No single "full name" column — just `First_Name` and `Last_Name` separately
- `Phone` values that are large negative numbers rather than anything resembling a real phone number
- Categorical fields worth knowing about up front: `Status` has **three** values
  (`Active` / `Pending` / `Inactive`), and `Performance_Score` is **text**
  (`Poor` / `Average` / `Good` / `Excellent`), not a 1–5 number

> The goal isn't "can you run Pandas?" — it's **"can you look at data and figure out what needs
> to happen next?"** Not every dataset is messy in the exact same way, which is exactly why we
> always inspect first instead of assuming.

## 3.0 Load the Data

In [13]:
import pandas as pd
import os

# Primary source: fetch straight from the GitHub repo (works anywhere with internet, incl. Colab)
RAW_URL = (
    "https://raw.githubusercontent.com/AbdouSalamSisawo/TensorOrbit-EDA-Bootcamp/"
    "main/day-1-foundations-pandas/materials/Messy_Employee_dataset.csv"
)

# Fallback: local paths, in case you're offline but have the repo cloned
LOCAL_CANDIDATES = [
    "Messy_Employee_dataset.csv",
    "materials/Messy_Employee_dataset.csv",
    "day-1-foundations-pandas/materials/Messy_Employee_dataset.csv",
]

df = None
try:
    df = pd.read_csv(RAW_URL)
    print(f"Loaded {df.shape[0]} rows directly from GitHub:\n{RAW_URL}")
except Exception as e:
    print(f"Could not fetch from GitHub ({e}).\nFalling back to a local copy...")
    for fname in LOCAL_CANDIDATES:
        if os.path.exists(fname):
            df = pd.read_csv(fname)
            print(f"Loaded local file '{fname}' instead.")
            break

if df is None:
    raise FileNotFoundError(
        "Could not load the dataset from GitHub or find it locally.\n"
        "Check your internet connection, or place the CSV at one of: "
        f"{LOCAL_CANDIDATES}"
    )

Loaded 1020 rows directly from GitHub:
https://raw.githubusercontent.com/AbdouSalamSisawo/TensorOrbit-EDA-Bootcamp/main/day-1-foundations-pandas/materials/Messy_Employee_dataset.csv

`pd.read_excel("file.xlsx")` works the same way for Excel files. `df` is now our entire
spreadsheet, living in memory as a DataFrame.

## 3.1 First Look at the Data — Shape & Structure

| Question | Tool |
|---|---|
| How big is my dataset? | `df.shape` |
| What variables do I have? | `df.columns` |
| What do the first rows look like? | `df.head()` |
| What about the last rows? | `df.tail()` |

In [14]:
print("Shape (rows, columns):", df.shape)
print("\nColumns:")
print(list(df.columns))

Shape (rows, columns): (1020, 12)

Columns:
['Employee_ID', 'First_Name', 'Last_Name', 'Age', 'Department_Region', 'Status', 'Join_Date', 'Salary', 'Email', 'Phone', 'Performance_Score', 'Remote_Work']

In [15]:
df.head()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False

In [16]:
df.tail()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
1015,EMP2015,David,Miller,30.0,HR-California,Active,8/19/2023,NaN,david.miller@example.com,-3546212759,Good,True
1016,EMP2016,David,Johnson,30.0,Cloud Tech-Texas,Inactive,11/7/2021,100215.06,david.johnson@example.com,-2508261122,Good,True
1017,EMP2017,Charlie,Williams,40.0,Finance-New York,Active,10/4/2023,114587.11,charlie.williams@example.com,-1261632487,Average,False
1018,EMP2018,Alice,Garcia,30.0,HR-Florida,Inactive,12/16/2024,71318.79,alice.garcia@example.com,-8995729892,Good,True
1019,EMP2019,Heidi,Jones,30.0,DevOps-Illinois,Pending,2/22/2021,77764.24,heidi.jones@example.com,-7629745492,Average,False

## 3.2 First Look at the Data — Types & Summary

| Question | Tool |
|---|---|
| What are the data types & missing values? | `df.info()` |
| What do the numeric columns look like? | `df.describe()` |

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1020 non-null   object
 1   First_Name         1020 non-null   object
 2   Last_Name          1020 non-null   object
 3   Age                809 non-null    float64
 4   Department_Region  1020 non-null   object
 5   Status             1020 non-null   object
 6   Join_Date          1020 non-null   object
 7   Salary             996 non-null    float64
 8   Email              1020 non-null   object
 9   Phone              1020 non-null   int64
 10  Performance_Score  1020 non-null   object
 11  Remote_Work        1020 non-null   bool
dtypes: bool(1), float64(2), int64(1), object(8)
memory usage: 88.8+ KB

In [18]:
df.describe()

              Age         Salary         Phone
count  809.000000     996.000000  1.020000e+03
mean    32.484549   85155.056396 -4.942253e+09
std      5.656860   19873.727918  2.817326e+09
min     25.000000   50047.320000 -9.994973e+09
25%     25.000000   68392.487500 -7.341992e+09
50%     30.000000   85547.870000 -4.943997e+09
75%     40.000000  100974.027500 -2.520391e+09
max     40.000000  119971.650000 -3.896086e+06

👀 **Look closely at `Phone` above.** The min/mean/max are all large *negative* numbers — that's
not what a real phone number looks like. Not every data-quality problem is a missing value or a
wrong dtype; sometimes a column is technically numeric but **doesn't mean anything real**. There's
no reliable way to recover genuine phone numbers from this, so the honest move is to flag it (as
we just did) rather than pretend we can fix it — and treat the column as an opaque identifier if
we ever need it, not as something to do arithmetic on.

## 3.3 Selecting Data

In [19]:
df["Salary"].head()

0     59767.65
1     65304.66
2     88145.90
3     69450.99
4    109324.61
Name: Salary, dtype: float64

In [20]:
df[["First_Name", "Last_Name", "Salary", "Department_Region"]].head()

  First_Name Last_Name     Salary   Department_Region
0        Bob     Davis   59767.65   DevOps-California
1        Bob     Brown   65304.66       Finance-Texas
2      Alice     Jones   88145.90        Admin-Nevada
3        Eva     Davis   69450.99        Admin-Nevada
4      Frank  Williams  109324.61  Cloud Tech-Florida

In [21]:
# .loc  -> select by label (row label, column name)
print(df.loc[0, "Salary"])

# .iloc -> select by position (row number, column number) — column 3 is Age
print(df.columns[3], "->", df.iloc[0, 3])

59767.65
Age -> 25.0

## 3.4 Filtering Data

Remember: `age > 30 and remote == True` from Part 1 — same logic, now applied to an entire
column instead of one variable. Note the syntax difference for multiple conditions:
use `&` instead of `and`, and wrap each condition in its own parentheses.

In [22]:
df[df["Age"] > 40].head()

Empty DataFrame
Columns: [Employee_ID, First_Name, Last_Name, Age, Department_Region, Status, Join_Date, Salary, Email, Phone, Performance_Score, Remote_Work]
Index: []

In [23]:
df[df["Status"] == "Active"].head()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False
6,EMP1006,Frank,Jones,NaN,Admin-Nevada,Active,4/3/2020,96288.43,frank.jones@example.com,-4518376063,Good,False
9,EMP1009,Charlie,Johnson,NaN,DevOps-New York,Active,8/4/2022,76561.88,charlie.johnson@example.com,-8156985699,Excellent,True

In [24]:
df[(df["Age"] > 30) & (df["Remote_Work"] == True)].head()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
8,EMP1008,Frank,Davis,35.0,Admin-Nevada,Inactive,12/8/2023,115565.82,frank.davis@example.com,-4177656123,Excellent,True
15,EMP1015,Grace,Jones,40.0,Sales-Florida,Pending,5/29/2021,117975.49,grace.jones@example.com,-4215291085,Good,True
19,EMP1019,Charlie,Williams,35.0,Admin-Illinois,Pending,1/2/2020,91926.12,charlie.williams@example.com,-7107256365,Average,True
20,EMP1020,Bob,Miller,35.0,HR-New York,Active,5/8/2021,111460.67,bob.miller@example.com,-9411800536,Excellent,True
22,EMP1022,Charlie,Johnson,35.0,Sales-Illinois,Inactive,3/9/2021,115023.94,charlie.johnson@example.com,-6528092427,Average,True

## 3.5 Sorting Data

*Who are the highest-paid employees?*

In [25]:
df.sort_values("Salary").head()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
394,EMP1394,Heidi,Williams,25.0,Cloud Tech-New York,Inactive,7/23/2022,50047.32,heidi.williams@example.com,-2407875417,Good,False
858,EMP1858,Heidi,Johnson,25.0,Finance-New York,Pending,8/4/2023,50060.73,heidi.johnson@example.com,-3176539704,Poor,False
782,EMP1782,Charlie,Garcia,NaN,Admin-Nevada,Inactive,1/31/2021,50110.66,charlie.garcia@example.com,-904637659,Average,True
549,EMP1549,Frank,Davis,40.0,Cloud Tech-Texas,Pending,3/30/2021,50153.79,frank.davis@example.com,-3758309450,Good,True
390,EMP1390,Eva,Williams,35.0,Finance-Florida,Inactive,4/6/2023,50173.12,eva.williams@example.com,-7637153987,Poor,False

In [26]:
df.sort_values("Salary", ascending=False).head()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
243,EMP1243,Charlie,Smith,NaN,Cloud Tech-Texas,Inactive,3/26/2022,119971.65,charlie.smith@example.com,-2831435988,Average,False
712,EMP1712,Grace,Smith,NaN,HR-Nevada,Active,12/29/2022,119890.35,grace.smith@example.com,-4991537037,Average,True
439,EMP1439,Bob,Williams,NaN,Sales-California,Active,2/14/2020,119801.30,bob.williams@example.com,-7753312660,Average,True
96,EMP1096,Frank,Johnson,40.0,Sales-Illinois,Inactive,5/21/2022,119764.20,frank.johnson@example.com,-8861405785,Average,False
444,EMP1444,Grace,Brown,30.0,DevOps-Illinois,Active,7/15/2023,119586.11,grace.brown@example.com,-9815287338,Average,True

In [27]:
df.nlargest(10, "Salary")

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
243,EMP1243,Charlie,Smith,NaN,Cloud Tech-Texas,Inactive,3/26/2022,119971.65,charlie.smith@example.com,-2831435988,Average,False
712,EMP1712,Grace,Smith,NaN,HR-Nevada,Active,12/29/2022,119890.35,grace.smith@example.com,-4991537037,Average,True
439,EMP1439,Bob,Williams,NaN,Sales-California,Active,2/14/2020,119801.30,bob.williams@example.com,-7753312660,Average,True
96,EMP1096,Frank,Johnson,40.0,Sales-Illinois,Inactive,5/21/2022,119764.20,frank.johnson@example.com,-8861405785,Average,False
444,EMP1444,Grace,Brown,30.0,DevOps-Illinois,Active,7/15/2023,119586.11,grace.brown@example.com,-9815287338,Average,True
103,EMP1103,Alice,Brown,30.0,Admin-Illinois,Inactive,6/23/2020,119574.27,alice.brown@example.com,-3985547434,Average,True
449,EMP1449,Alice,Miller,30.0,Sales-Florida,Inactive,9/14/2024,119407.93,alice.miller@example.com,-8469081973,Excellent,True
896,EMP1896,Charlie,Miller,NaN,Cloud Tech-Florida,Active,3/23/2020,119389.15,charlie.miller@example.com,-9223410345,Poor,False
731,EMP1731,Alice,Smith,35.0,Admin-California,Pending,8/9/2024,119311.14,alice.smith@example.com,-2835129591,Poor,True
157,EMP1157,David,Johnson,NaN,Cloud Tech-Texas,Inactive,5/13/2021,119217.46,david.johnson@example.com,-2316433480,Poor,False

## 3.6 Descriptive Statistics

- What is the average employee age?
- What is the median salary?
- How many employees are Active vs Pending vs Inactive?
- What is the highest salary in the dataset?

In [28]:
print("Average age:", round(df["Age"].mean(), 1))
print("Median salary:", df["Salary"].median())

Average age: 32.5
Median salary: 85547.87

In [29]:
df["Status"].value_counts()

Status
Pending     356
Active      352
Inactive    312
Name: count, dtype: int64

## 3.7 Missing Values

Missing data is **not automatically "bad"** — first we investigate:
- How much is missing? Which columns? Why might it be missing? What should we do?

`fillna()` replaces gaps; `dropna()` removes rows entirely — the right choice depends on the question.

In [30]:
df.isnull().sum()

Employee_ID            0
First_Name             0
Last_Name              0
Age                  211
Department_Region      0
Status                 0
Join_Date              0
Salary                24
Email                  0
Phone                  0
Performance_Score      0
Remote_Work            0
dtype: int64

In [31]:
# Example: fill missing Age with the median age (a common, defensible default)
age_filled = df["Age"].fillna(df["Age"].median())
print("Missing before:", df["Age"].isnull().sum())
print("Missing after: ", age_filled.isnull().sum())

Missing before: 211
Missing after:  0

In [32]:
# Example: drop rows that are missing ANY value (use with care — inspect first!)
df_complete_rows_only = df.dropna()
print("Rows before dropna:", len(df))
print("Rows after dropna: ", len(df_complete_rows_only))

Rows before dropna: 1020
Rows after dropna:  787

## 3.8 Duplicates

If the same employee appears twice, counts and averages become misleading.

In [33]:
print("Number of duplicate rows:", df.duplicated().sum())
df[df.duplicated(keep=False)].head(10)

Number of duplicate rows: 0

Empty DataFrame
Columns: [Employee_ID, First_Name, Last_Name, Age, Department_Region, Status, Join_Date, Salary, Email, Phone, Performance_Score, Remote_Work]
Index: []

In [34]:
df_no_duplicates = df.drop_duplicates()
print("Rows before:", len(df))
print("Rows after: ", len(df_no_duplicates))

Rows before: 1020
Rows after:  1020

## 3.9 Data Types & Conversion

`df.dtypes` tells us what Pandas thinks each column holds. In this dataset, `Salary` and `Age`
already loaded as real numbers, and `Remote_Work` loaded as a real boolean — but `Join_Date` is
still plain text, so date-specific tools (like `.dt.year`) won't work on it yet.

In [35]:
df.dtypes

Employee_ID           object
First_Name            object
Last_Name             object
Age                  float64
Department_Region     object
Status                object
Join_Date             object
Salary               float64
Email                 object
Phone                  int64
Performance_Score     object
Remote_Work             bool
dtype: object

In [36]:
df["Join_Date_Parsed"] = pd.to_datetime(df["Join_Date"], errors="coerce")

print("Unparseable Join_Date values:", df["Join_Date_Parsed"].isnull().sum())
df[["Join_Date", "Join_Date_Parsed"]].head()

Unparseable Join_Date values: 0

    Join_Date Join_Date_Parsed
0    4/2/2021       2021-04-02
1   7/10/2020       2020-07-10
2   12/7/2023       2023-12-07
3  11/27/2021       2021-11-27
4    1/5/2022       2022-01-05

**Not every dataset is this clean, though.** It's very common for a `Salary`-style column to
arrive as text — things like `"$85,000"` or `"N/A"` — which breaks `.mean()` exactly like the
`"25" + 5` error from section 1.2. The defensive pattern below (`pd.to_numeric(..., errors="coerce")`)
is worth knowing even though *this particular* dataset doesn't need it for `Salary`:

In [37]:
# A small illustrative example — not our real data, just the general technique
messy_salary_example = pd.Series(["85000", "$92,000", "N/A", "110000"])
cleaned_example = pd.to_numeric(
    messy_salary_example.str.replace(r"[^0-9.\-]", "", regex=True),
    errors="coerce",
)
print(cleaned_example.tolist())

[85000.0, 92000.0, nan, 110000.0]

**One more type worth adjusting:** `Phone` loaded as a number (`int64`), but we already saw it
doesn't represent anything real. Casting it to text makes that intent explicit — it's an
identifier-like field, not a quantity:

In [38]:
df["Phone"] = df["Phone"].astype(str)
df["Phone"].head()

0    -1651623197
1    -1898471390
2    -5596363211
3    -3476490784
4    -1586734256
Name: Phone, dtype: object

## 3.10 Creating & Modifying Columns

New columns can be built from existing ones — this is called **feature creation**. There's no
single "full name" column in this dataset, only `First_Name` and `Last_Name` — a perfect
opportunity to build one ourselves.

In [39]:
df["Full_Name"] = df["First_Name"] + " " + df["Last_Name"]
df[["First_Name", "Last_Name", "Full_Name"]].head()

  First_Name Last_Name       Full_Name
0        Bob     Davis       Bob Davis
1        Bob     Brown       Bob Brown
2      Alice     Jones     Alice Jones
3        Eva     Davis       Eva Davis
4      Frank  Williams  Frank Williams

In [40]:
# Salary here reads as an annual figure (values sit in the ~$50k–$120k range),
# so a natural derived column is the monthly equivalent
df["Monthly_Salary"] = df["Salary"] / 12
df[["Salary", "Monthly_Salary"]].head()

      Salary  Monthly_Salary
0   59767.65     4980.637500
1   65304.66     5442.055000
2   88145.90     7345.491667
3   69450.99     5787.582500
4  109324.61     9110.384167

**Bonus — splitting a compound column:** `Department_Region` mixes two variables together
(e.g. `"DevOps-California"`). We can split it into two clean columns using the same `.str` tools
from the next section:

In [41]:
split_cols = df["Department_Region"].astype(str).str.split("-", n=1, expand=True)
df["Department"] = split_cols[0]
df["Region"] = split_cols[1]
df[["Department_Region", "Department", "Region"]].head()

    Department_Region  Department      Region
0   DevOps-California      DevOps  California
1       Finance-Texas     Finance       Texas
2        Admin-Nevada       Admin      Nevada
3        Admin-Nevada       Admin      Nevada
4  Cloud Tech-Florida  Cloud Tech     Florida

## 3.11 String Operations

The `.str` accessor applies string methods to an entire column at once — the exact same
`.strip()` / `.lower()` methods from section 1.4, now running on every row simultaneously.

In [42]:
df["Full_Name"] = df["Full_Name"].astype(str).str.strip()
df["Full_Name_Lower"] = df["Full_Name"].str.lower()
df[["Full_Name", "Full_Name_Lower"]].head()

        Full_Name Full_Name_Lower
0       Bob Davis       bob davis
1       Bob Brown       bob brown
2     Alice Jones     alice jones
3       Eva Davis       eva davis
4  Frank Williams  frank williams

In [43]:
looks_like_gmail = df["Email"].astype(str).str.contains("@gmail", case=False, na=False)
print("Employees with a gmail address:", looks_like_gmail.sum())

Employees with a gmail address: 0

Every email in this dataset actually uses the same placeholder domain (`@example.com`), so that
count above is expected to be `0` — the point isn't the result, it's that you can't know that
without checking. On a real HR export you'd often find a genuine mix of work and personal domains.

## 3.12 Working With Dates

*What year did most employees join?*

In [44]:
df["Join_Year"] = df["Join_Date_Parsed"].dt.year
df["Join_Month"] = df["Join_Date_Parsed"].dt.month
df["Join_Weekday"] = df["Join_Date_Parsed"].dt.day_name()

df[["Join_Date_Parsed", "Join_Year", "Join_Month", "Join_Weekday"]].head()

  Join_Date_Parsed  Join_Year  Join_Month Join_Weekday
0       2021-04-02       2021           4       Friday
1       2020-07-10       2020           7       Friday
2       2023-12-07       2023          12     Thursday
3       2021-11-27       2021          11     Saturday
4       2022-01-05       2022           1    Wednesday

In [45]:
df["Join_Year"].value_counts().sort_index()

Join_Year
2020    203
2021    189
2022    183
2023    228
2024    217
Name: count, dtype: int64

## 3.13 GroupBy & Aggregation

`groupby` = **split → apply → combine**. This is one of the most powerful tools in Pandas.

- Which department/region has the highest average salary?
- How many employees are in each status?
- What is the average salary by performance score?

In [46]:
df.groupby("Department")["Salary"].mean().sort_values(ascending=False)

Department
Sales         86896.681029
DevOps        86016.023641
HR            85473.643174
Admin         85191.922795
Cloud Tech    84923.036241
Finance       82240.610417
Name: Salary, dtype: float64

In [47]:
df.groupby("Status")["Salary"].agg(["count", "mean", "min", "max"])

          count          mean       min        max
Status
Active      343  85129.264752  50288.67  119890.35
Inactive    300  84501.909733  50047.32  119971.65
Pending     353  85735.199547  50060.73  119311.14

In [48]:
df.groupby("Performance_Score")["Salary"].mean().sort_values(ascending=False)

Performance_Score
Good         86338.758654
Excellent    85044.753615
Poor         85035.907371
Average      84190.398137
Name: Salary, dtype: float64

## 3.14 Merge & Concat

`concat` stacks datasets on top of each other; `merge` joins them side-by-side using a
shared key column. Here we build a small department lookup table and merge it back onto
our employee data, purely to demonstrate the pattern.

In [49]:
departments = pd.DataFrame({
    "Department": df["Department"].dropna().unique(),
})
departments["Department_Head_Count_Target"] = range(10, 10 + len(departments))
departments

   Department  Department_Head_Count_Target
0      DevOps                            10
1     Finance                            11
2       Admin                            12
3  Cloud Tech                            13
4       Sales                            14
5          HR                            15

In [50]:
merged = pd.merge(df, departments, on="Department", how="left")
merged[["Full_Name", "Department", "Department_Head_Count_Target"]].head()

        Full_Name  Department  Department_Head_Count_Target
0       Bob Davis      DevOps                            10
1       Bob Brown     Finance                            11
2     Alice Jones       Admin                            12
3       Eva Davis       Admin                            12
4  Frank Williams  Cloud Tech                            13

In [51]:
# concat example: stacking two halves of the dataset back together
half_1 = df.iloc[: len(df) // 2]
half_2 = df.iloc[len(df) // 2 :]
stacked = pd.concat([half_1, half_2])
print("Original rows:", len(df), "| Stacked rows:", len(stacked))

Original rows: 1020 | Stacked rows: 1020

## 3.15 Exporting Cleaned Data

Analysis usually ends by producing a clean dataset for someone else — a colleague, a
dashboard, or a model.

In [52]:
df.to_csv("cleaned_employee_data.csv", index=False)
print("Saved cleaned_employee_data.csv with", df.shape[0], "rows and", df.shape[1], "columns.")

Saved cleaned_employee_data.csv with 1020 rows and 21 columns.

---
# Part 4 — Guided EDA Challenge

Your turn. Work through each question below **using the tools from Part 3**. Think before you
type — for each one, ask yourself *"what would I do first?"* before writing any code.

Use `df` (the added columns like `Salary`, `Join_Date_Parsed`, `Department`, `Region`
are available) or go back to the original raw columns — your choice.

**1.** How many employees are in the dataset?

In [53]:
# Your code here

**2.** How many columns are there?

In [54]:
# Your code here

**3.** Which columns contain missing values?

In [55]:
# Your code here

**4.** How many duplicate records exist?

In [56]:
# Your code here

**5.** What is the average age?

In [57]:
# Your code here

**6.** What is the median salary?

In [58]:
# Your code here

**7.** Which employees have the highest salaries?

In [59]:
# Your code here

**8.** What is the Active/Inactive status distribution?

In [60]:
# Your code here

**9.** Which department-region has the highest average salary?

In [61]:
# Your code here

**10.** What is the split between remote and non-remote employees?

In [62]:
# Your code here

**11.** What problems do you notice with Join_Date?

In [63]:
# Your code here

**12.** What problems do you notice with Salary?

In [64]:
# Your code here

**13.** What data-cleaning steps would you recommend overall?

In [65]:
# Your code here

---
# Part 5 — Recap & What's Next

**Today we covered:**
- ✓ Python fundamentals for data analysis (variables, types, operators, strings, lists,
  dictionaries, conditions, loops, functions, imports)
- ✓ Pandas basics — Series & DataFrame
- ✓ Loading and inspecting a real messy dataset
- ✓ Selecting, filtering, and sorting data
- ✓ Descriptive statistics
- ✓ Handling missing values and duplicates
- ✓ Fixing data types (text-stored numbers, inconsistent dates)
- ✓ Creating and modifying columns, string cleaning, datetime parts
- ✓ GroupBy & aggregation
- ✓ Merge/concat and exporting cleaned data

> **"Don't just clean the data. Ask questions about it."**

**Coming up:**
- **Day 2:** NumPy + Matplotlib
- **Day 3:** Applied EDA + Capstone project

— Abdou Salam Sisawo · TensorOrbit EDA Bootcamp